# Generated by Django 4.1 on 2023-06-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_lesson_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lesson_plans',
            field=models.ManyToManyField(blank=True, related_name='lesson_plan', to='core.lessonplan'),
        ),
    ]
