# Generated by Django 4.1.3 on 2023-07-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_lesson_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='lesson_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
