# Generated by Django 4.1.3 on 2023-07-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lessonplan_date_created_lessonplan_lesson_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='associated_teachers',
            field=models.ManyToManyField(blank=True, related_name='associated_teachers', to='core.profile'),
        ),
    ]
