# Generated by Django 4.1 on 2023-07-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_profile_lesson_plans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='core.profile'),
        ),
    ]
