# Generated by Django 4.1 on 2023-07-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lessonplan_slug_alter_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=75, null=True, unique=True),
        ),
    ]
