# Generated by Django 4.1 on 2023-07-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_lessonplan_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='subject',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='core.subject'),
        ),
    ]
