# Generated by Django 4.1 on 2023-07-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_lessonplan_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='core.subject'),
        ),
    ]
