# Generated by Django 4.1.3 on 2023-07-28 05:08

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_lessonplan_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='text_content',
            field=models.TextField(validators=[core.validators.validate_existence]),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, validators=[core.validators.validate_existence]),
        ),
    ]
